# Generated by Django 2.1.5 on 2019-03-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_auto_20190310_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Verified', 'Verified'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
