# Generated by Django 2.1.5 on 2019-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_auto_20190310_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Verified', 'Verified'), ('Processing', 'Processing'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
